<?php
require_once 'config/db.php';

$ref = strtoupper(trim($_GET['ref'] ?? $_GET['r'] ?? ''));
$letter = null;

if ($ref !== '') {
    $stmt = $pdo->prepare(
        "SELECT rl.ref_no, rl.generated_at, u.full_name, u.username, u.role, u.created_at AS cashier_created_at,
                admin.full_name AS generated_by_name
         FROM recommendation_letters rl
         JOIN users u ON u.id = rl.user_id
         LEFT JOIN users admin ON admin.id = rl.generated_by
         WHERE rl.ref_no = ?
         LIMIT 1"
    );
    $stmt->execute([$ref]);
    $letter = $stmt->fetch(PDO::FETCH_ASSOC);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify Recommendation</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { min-height: 100vh; background: #f4f7fb; display: grid; place-items: center; padding: 24px; }
        .verify-card { width: min(720px, 100%); border: 0; border-radius: 8px; box-shadow: 0 16px 40px rgba(20, 35, 55, 0.12); }
        .brand-logo { width: 72px; height: 72px; object-fit: contain; }
        .detail-label { color: #667085; font-size: 0.88rem; margin-bottom: 2px; }
        .detail-value { font-weight: 600; overflow-wrap: anywhere; }
    </style>
</head>
<body>
    <main class="card verify-card">
        <div class="card-body p-4 p-md-5">
            <div class="d-flex align-items-center gap-3 mb-4">
                <img src="assets/DELIGOS%20LOGO.png" class="brand-logo" alt="Deligos Company">
                <div>
                    <h1 class="h4 mb-1">Recommendation Verification</h1>
                    <div class="text-muted">Deligos Company</div>
                </div>
            </div>

            <?php if ($ref === ''): ?>
                <div class="alert alert-warning mb-0">Enter a recommendation reference number to verify this letter.</div>
            <?php elseif (!$letter): ?>
                <div class="alert alert-danger mb-4">No valid recommendation letter was found for this reference number.</div>
                <div class="detail-label">Reference checked</div>
                <div class="detail-value"><?= htmlspecialchars($ref) ?></div>
            <?php else: ?>
                <div class="alert alert-success mb-4">This recommendation letter is valid in the Deligos POS system.</div>
                <div class="row g-3">
                    <div class="col-md-6">
                        <div class="detail-label">Reference number</div>
                        <div class="detail-value"><?= htmlspecialchars($letter['ref_no']) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div class="detail-label">Generated on</div>
                        <div class="detail-value"><?= htmlspecialchars(date('F j, Y g:i A', strtotime($letter['generated_at']))) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div class="detail-label">Recommended cashier</div>
                        <div class="detail-value"><?= htmlspecialchars($letter['full_name'] ?: $letter['username']) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div class="detail-label">Role</div>
                        <div class="detail-value"><?= htmlspecialchars(ucfirst($letter['role'])) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div class="detail-label">Cashier since</div>
                        <div class="detail-value"><?= htmlspecialchars(date('F j, Y', strtotime($letter['cashier_created_at']))) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div class="detail-label">Generated by</div>
                        <div class="detail-value"><?= htmlspecialchars($letter['generated_by_name'] ?: 'System') ?></div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </main>
</body>
</html>
